#!/usr/bin/env node

/**
 * LogInTo — Setup Script
 *
 * Guides you through initial setup:
 * 1. Create .env file with your password
 * 2. Check system dependencies
 * 3. Grant screen capture permissions (macOS)
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');
const { execSync } = require('child_process');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, resolve);
  });
}

async function setup() {
  console.log('');
  console.log('═══════════════════════════════════════════');
  console.log('   🖥️  LogInTo — Setup Wizard');
  console.log('═══════════════════════════════════════════');
  console.log('');

  // Step 1: Password
  console.log('📋 Step 1: Set your access password');
  console.log('   This is what you\'ll enter on your phone to connect.\n');

  let password = await ask('   Enter a password: ');
  while (!password || password.length < 4) {
    console.log('   ⚠️  Password must be at least 4 characters');
    password = await ask('   Enter a password: ');
  }

  // Step 2: Port
  console.log('');
  const portStr = await ask('   Server port (default 3456): ');
  const port = parseInt(portStr) || 3456;

  // Step 3: Generate .env
  const sessionSecret = crypto.randomBytes(32).toString('hex');
  const envContent = `# LogInTo Configuration
# Generated by setup wizard

# Your access password
ACCESS_PASSWORD=${password}

# Server port
PORT=${port}

# Session secret (auto-generated)
SESSION_SECRET=${sessionSecret}

# Screen capture settings
# Quality: 10-100 (higher = better quality, more bandwidth)
CAPTURE_QUALITY=60

# FPS: 1-30 (higher = smoother, more CPU)
CAPTURE_FPS=15

# Scale: 0.1-1.0 (lower = faster, less detail)
CAPTURE_SCALE=0.5

# Security
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_MINUTES=15
`;

  const envPath = path.join(__dirname, '..', '.env');
  fs.writeFileSync(envPath, envContent);
  console.log('\n   ✅ Configuration saved to .env');

  // Step 4: Platform-specific checks
  console.log('\n📋 Step 2: System check\n');

  const platform = process.platform;

  if (platform === 'darwin') {
    console.log('   🍎 macOS detected');
    console.log('');
    console.log('   ⚠️  IMPORTANT: You need to grant Screen Recording permission');
    console.log('   Go to: System Settings → Privacy & Security → Screen Recording');
    console.log('   Add "Terminal" (or your terminal app) to the allowed list.');
    console.log('');
    console.log('   Also grant Accessibility permission for input control:');
    console.log('   System Settings → Privacy & Security → Accessibility');
    console.log('');
  } else if (platform === 'linux') {
    console.log('   🐧 Linux detected');
    try {
      execSync('which xdotool', { stdio: 'ignore' });
      console.log('   ✅ xdotool found (for input control)');
    } catch {
      console.log('   ⚠️  xdotool not found. Install with:');
      console.log('      sudo apt install xdotool');
    }
  } else if (platform === 'win32') {
    console.log('   🪟 Windows detected');
    console.log('   ✅ No special permissions needed');
  }

  // Step 5: Check node version
  const nodeVersion = process.version;
  const major = parseInt(nodeVersion.slice(1));
  if (major < 18) {
    console.log(`\n   ⚠️  Node.js ${nodeVersion} detected. Version 18+ recommended.`);
  } else {
    console.log(`\n   ✅ Node.js ${nodeVersion}`);
  }

  // Done
  console.log('');
  console.log('═══════════════════════════════════════════');
  console.log('   ✅ Setup complete!');
  console.log('');
  console.log('   To start the server:');
  console.log('     npm start');
  console.log('');
  console.log('   Then open the URL on your phone 📱');
  console.log('═══════════════════════════════════════════');
  console.log('');

  rl.close();
}

setup().catch(err => {
  console.error('Setup failed:', err);
  rl.close();
  process.exit(1);
});
